In [6]:
import pandas as pd

In [7]:
datos = pd.read_csv('./data/juego_tennis.csv')

In [8]:
datos

   Pronóstico Temperatura Humedad Viento Juega_Tennis
0     soleado       calor    alta     no           No
1     soleado       calor    alta     si           No
2     nublado       calor    alta     no           Si
3    lluvioso    moderado    alta     no           Si
4    lluvioso        frío  normal     no           Si
5    lluvioso        frío  normal     si           No
6     nublado        frío  normal     si           Si
7     soleado    moderado    alta     no           No
8     soleado        frío  normal     no           Si
9    lluvioso    moderado  normal     no           Si
10    soleado    moderado  normal     si           Si
11    nublado    moderado    alta     si           Si
12    nublado       calor  normal     no           Si
13   lluvioso    moderado    alta     si           No

In [9]:
condicion = (datos['Pronóstico'] == 'nublado')
datos = datos.drop(datos[condicion].index)

In [10]:
datos

   Pronóstico Temperatura Humedad Viento Juega_Tennis
0     soleado       calor    alta     no           No
1     soleado       calor    alta     si           No
3    lluvioso    moderado    alta     no           Si
4    lluvioso        frío  normal     no           Si
5    lluvioso        frío  normal     si           No
7     soleado    moderado    alta     no           No
8     soleado        frío  normal     no           Si
9    lluvioso    moderado  normal     no           Si
10    soleado    moderado  normal     si           Si
13   lluvioso    moderado    alta     si           No

In [11]:
condicion = (datos['Humedad'] == 'alta')
hummedad_alta_no = datos.drop(datos[condicion].index)

condicion = (datos['Humedad'] == 'normal')
hummedad_alta_si = datos.drop(datos[condicion].index)

In [12]:
hummedad_alta_no

   Pronóstico Temperatura Humedad Viento Juega_Tennis
4    lluvioso        frío  normal     no           Si
5    lluvioso        frío  normal     si           No
8     soleado        frío  normal     no           Si
9    lluvioso    moderado  normal     no           Si
10    soleado    moderado  normal     si           Si

In [13]:
hummedad_alta_si

   Pronóstico Temperatura Humedad Viento Juega_Tennis
0     soleado       calor    alta     no           No
1     soleado       calor    alta     si           No
3    lluvioso    moderado    alta     no           Si
7     soleado    moderado    alta     no           No
13   lluvioso    moderado    alta     si           No

In [14]:
condicion = (hummedad_alta_no['Viento'] == 'no')
viento_si = hummedad_alta_no.drop(hummedad_alta_no[condicion].index)

In [18]:
viento_si

   Pronóstico Temperatura Humedad Viento Juega_Tennis
5    lluvioso        frío  normal     si           No
10    soleado    moderado  normal     si           Si

In [19]:
condicion = (hummedad_alta_si['Pronóstico'] == 'soleado')
viento_no = hummedad_alta_si.drop(hummedad_alta_si[condicion].index)

In [20]:
viento_no

   Pronóstico Temperatura Humedad Viento Juega_Tennis
3    lluvioso    moderado    alta     no           Si
13   lluvioso    moderado    alta     si           No

In [15]:
import math

def entropia(a, b):
    return -a/(a+b)*math.log2(a/(a+b)) - b/(a+b)*math.log2(b/(a+b))